### ISSUE TITLE
Release 0.0.1 intentionally without the "v" prefix?

### ISSUE THREAD

**Issue by kastl-ars** [alexellis/kubetrim#7]
Hi Alex,

just a short question: Is it intentional that the 0.0.1 release comes without the leading "v" prefix that the release candidates had?

Kind Regards,
Johannes

P.S.: Thanks a lot for another useful tool!

**Comment by alexellis** [comment]
Hi @kastl-ars there's a mix of components that use the v prefix and ones that don't, looks like this was a mistake, so I'll release it as v0.0.1.

Glad you find my tools useful, check out the [options for GitHub Sponsorships](https://github.com/sponsors/alexellis).

More sponsors = more tools, and more attention on them.

**Comment by kastl-ars** [comment]
Thanks for fixing, that was quick!
